version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade pip
      - pip3 install boto3
  build:
    commands:
      - cd guardduty-cti-automations
      - python3 gd-loads.py
  post_build:
    commands:
      - echo GuardDuty threat intel set updates completed on `date`