version: 0.2

phases:
  install:
    commands:
      - pip3 install --upgrade pip
      - pip3 install boto3
  build:
    commands:
      - cd waf-cti-automations
      - python3 waf-loads.py
  post_build:
    commands:
      - echo WAFv2 IP Set updates completed on `date`