AWSTemplateFormatVersion: 2010-09-09
Description: Creates the threat intel automation services needed for SyntheticSun such as DynamoDB and CodeBuild assets. Deploy this second.
Parameters:
  ArtifactsBucketName:
    Type: String
    Description: Name of the S3 bucket where SyntheticSun artifacts were uploaded in Stage 1
  MISPInstanceId:
    Type: String
    Description: The Instance ID of the MISP instance created in Stage 1
  MISPAutomationKeyParameter:
    Type: String
    Description: The name of the SSM Parameter that contains the MISP automation key
    Default: MISP-Automation-Key
  ThreatIntelWAFIpSetName:
    Type: String
    Description: The name of the threat intel WAF IP Set created in Stage 1
    Default: CTI-Blocklist-IPSet
  ThreatIntelWAFIpSetId:
    Type: String
    Description: The logical ID of the threat intel WAF IP Set created in Stage 1
  IpInsightsIntelWAFIpSetName:
    Type: String
    Description: The name of the IP Insights WAF IP Set created in Stage 1
    Default: IPInsights-Blocklist-IPSet
  IpInsightsIntelWAFIpSetId:
    Type: String
    Description: The logical ID of the IP Insights WAF IP Set created in Stage 1
  GuardDutyDetectorId:
    Type: String
    Description: The Detector ID for GuardDuty in the region you are deploying SyntheticSun
Resources:
  CTIThreatIntelSet:
    Type: AWS::GuardDuty::ThreatIntelSet
    Properties: 
      Activate: true
      DetectorId: !Ref GuardDutyDetectorId
      Format: TXT
      Location: !Sub 'https://s3-${AWS::Region}.amazonaws.com/${ArtifactsBucketName}/cti-threatlist.txt'
      Name: cti-threatlist
  IpInsightsThreatIntelSet:
    Type: AWS::GuardDuty::ThreatIntelSet
    Properties: 
      Activate: true
      DetectorId: !Ref GuardDutyDetectorId
      Format: TXT
      Location: !Sub 'https://s3-${AWS::Region}.amazonaws.com/${ArtifactsBucketName}/anomaly-threatlist.txt'
      Name: ipinsights-threatlist
  SyntheticSunCICDCodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: Contains SyntheticSun Stage 2 build automation artifacts - Managed by CloudFormation
      RepositoryName: syntheticsun-cti-automations
      Code:
        S3:
          Bucket: !Ref ArtifactsBucketName
          Key: syntheticsun-codecommit.zip
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SyntheticSun-CodebuildRole
      Policies:
      - PolicyName: SyntheticSun-CodeBuildServiceRolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - codecommit:GitPull
            Resource: !GetAtt SyntheticSunCICDCodeCommit.Arn
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:PutObject
            - s3:GetBucketAcl
            - s3:GetBucketLocation
            Resource: '*'
          - Effect: Allow
            Action:
            - guardduty:GetThreatIntelSet
            - guardduty:UpdateThreatIntelSet
            - wafv2:GetIPSet
            - wafv2:UpdateIPSet
            - kms:Decrypt
            - ssm:GetParameter
            - ssm:GetParameters
            Resource: '*'
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            Resource: !GetAtt IPIoCDDB.Arn
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            Resource: !GetAtt DomainIoCDDB.Arn
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            Resource: !GetAtt IPInsightsDDB.Arn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: { Service: codebuild.amazonaws.com }
          Action:
          - sts:AssumeRole
  CodeBuildEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SyntheticSun-CodeBuild-Sched-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: { Service: events.amazonaws.com }
          Action:
          - codebuild:StartProject
  MISPAutomationsCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Performs tag-based loading of latest cyber threat intelligence IOCs from MISP server into DynamoDB tables for SyntheticSun - Managed by CloudFormation
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: True
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: MISP_AUTOMATION_KEY_PARAMETER
          Type: PLAINTEXT
          Value: !Ref MISPAutomationKeyParameter
        - Name: MISP_EC2_ID
          Type: PLAINTEXT
          Value: !Ref MISPInstanceId
        - Name: MISP_IP_IOC_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref IPIoCDDB
        - Name: MISP_DOMAIN_IOC_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref DomainIoCDDB
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Name: SyntheticSun-MISP-Automations
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        BuildSpec: misp-automations/buildspec.yaml
        Type: CODECOMMIT
  MISPAutomationsCodeBuildEvent: 
    Type: AWS::Events::Rule
    Properties:
      Name: SyntheticSun-MISP-Automations-Rule
      Description: Runs SyntheticSun-MISP-Automations every 4 hours - Managed by CloudFormation
      ScheduleExpression: rate(4 hours)
      RoleArn: !GetAtt CodeBuildEventRole.Arn
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt MISPAutomationsCodeBuild.Arn
          Id: GDAutomationTrigger
  LIMOAutomationsCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Performs collection-based loading of latest cyber threat intelligence IOCs from Anomali's LIMO TAXII/STIX feed into DynamoDB tables for SyntheticSun - Managed by CloudFormation
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: True
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: MISP_IP_IOC_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref IPIoCDDB
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Name: SyntheticSun-LIMO-Automations
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        BuildSpec: limo-automations/buildspec.yaml
        Type: CODECOMMIT
  LIMOAutomationsCodeBuildEvent: 
    Type: AWS::Events::Rule
    Properties:
      Name: SyntheticSun-LIMO-Automations-Rule
      Description: Runs SyntheticSun-LIMO-Automations every 4 hours - Managed by CloudFormation
      ScheduleExpression: rate(4 hours)
      RoleArn: !GetAtt CodeBuildEventRole.Arn
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt LIMOAutomationsCodeBuild.Arn
          Id: GDAutomationTrigger
  WAFAutomationsCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Performs weekly updates of WAF IP Sets based on latest cyber threat intelligence and IP Insights anomalies - Managed by CloudFormation
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: True
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: MISP_IP_IOC_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref IPIoCDDB
        - Name: WAF_CTI_IP_SET_ID
          Type: PLAINTEXT
          Value: !Ref ThreatIntelWAFIpSetId
        - Name: WAF_CTI_IP_SET_NAME
          Type: PLAINTEXT
          Value: !Ref ThreatIntelWAFIpSetName
        - Name: IP_INSIGHTS_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref IPInsightsDDB
        - Name: IP_INSIGHTS_IP_SET_ID
          Type: PLAINTEXT
          Value: !Ref IpInsightsIntelWAFIpSetId
        - Name: IP_INSIGHTS_IP_SET_NAME
          Type: PLAINTEXT
          Value: !Ref IpInsightsIntelWAFIpSetName
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Name: SyntheticSun-WAF-Automations
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        BuildSpec: waf-cti-automations/buildspec.yaml
        Type: CODECOMMIT
  WAFAutomationsCodeBuildEvent: 
    Type: AWS::Events::Rule
    Properties:
      Name: SyntheticSun-WAF-Automations-Rule
      Description: Runs SyntheticSun-WAF-Automations every 6 days - Managed by CloudFormation
      ScheduleExpression: rate(6 days)
      RoleArn: !GetAtt CodeBuildEventRole.Arn
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt WAFAutomationsCodeBuild.Arn
          Id: GDAutomationTrigger
  GuardDutyAutomationsCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Performs weekly updates of GuardDuty threat intel sets based on latest cyber threat intelligence and IP Insights anomalies - Managed by CloudFormation
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: True
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: SYNTHETIC_SUN_ARTIFACT_BUCKET
          Type: PLAINTEXT
          Value: !Ref ArtifactsBucketName
        - Name: MISP_IP_IOC_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref IPIoCDDB
        - Name: IP_INSIGHTS_DDB_TABLE
          Type: PLAINTEXT
          Value: !Ref IPInsightsDDB
        - Name: GUARDDUTY_DETECTOR_ID
          Type: PLAINTEXT
          Value: !Ref GuardDutyDetectorId
        - Name: CTI_THREAT_INTEL_SET_ID
          Type: PLAINTEXT
          Value: !Ref CTIThreatIntelSet
        - Name: ANOMALY_THREAT_INTEL_SET_ID
          Type: PLAINTEXT
          Value: !Ref IpInsightsThreatIntelSet
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Name: SyntheticSun-GuardDuty-Automations
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        BuildSpec: guardduty-cti-automations/buildspec.yaml
        Type: CODECOMMIT
  GuardDutyAutomationsCodeBuildEvent: 
    Type: AWS::Events::Rule
    Properties:
      Name: SyntheticSun-GuardDuty-Automations-Rule
      Description: Runs SyntheticSun-GuardDuty-Automations every 6 days - Managed by CloudFormation
      ScheduleExpression: rate(6 days)
      RoleArn: !GetAtt CodeBuildEventRole.Arn
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt GuardDutyAutomationsCodeBuild.Arn
          Id: GDAutomationTrigger
  IPIoCDDB: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: IPV4_IOC
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: IPV4_IOC
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      TableName: IP-IOC-Threat-Intel
  DomainIoCDDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: DOMAIN_IOC
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: DOMAIN_IOC
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      TableName: Domain-IOC-Threat-Intel
  IPInsightsDDB: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: ANOMALY_IPV4
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: ANOMALY_IPV4
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: IP-Insights-Anomalies